import theorielearn.fooling_sets.server_base as server_base


def generate(data):
    data["params"]["language_description"] = r"""The language $L$ of properly balanced strings of parentheses over $\Sigma = \{\ \mathtt{(},\ \mathtt{)}\ \}$, generated by $S \to \varepsilon \mid SS \mid (S)$."""
    server_base.generate(data)
