from typing import List, Optional, Sequence, Type, TypeVar, Union

class Nonterminal:
    def __init__(self, symbol: str) -> None: ...
    def symbol(self) -> str: ...

TerminalT = str
SymbolT = Union[Nonterminal, TerminalT]

class Production:
    def lhs(self) -> Nonterminal: ...
    def rhs(self) -> Sequence[SymbolT]: ...

# See here for explanation of why the TypeVar is needed:
# https://github.com/python/typing/issues/254#issuecomment-661803922
T = TypeVar("T", bound=CFG)

class CFG:
    def __init__(self, start: Nonterminal, productions: List[Production]) -> None: ...
    @classmethod
    def fromstring(cls: Type[T], input: str, encoding: Optional[str] = None) -> T: ...
    def productions(
        self, lhs: Optional[Nonterminal] = None, rhs: Optional[SymbolT] = None, empty: bool = False
    ) -> List[Production]: ...
    def start(self) -> Nonterminal: ...
