from types import ModuleType
from typing import Callable, Any

def points(points: float) -> Callable[..., Callable[..., Any]]: ...
def name(name: str) -> Callable[..., Callable[..., None]]: ...
def not_repeated(f: Callable[..., Any]) -> Callable[..., None]: ...
def print_student_code(
    st_code: str = "user_code.py",
    ipynb_key: str = "#grade",
    as_feedback: bool = True,  # noqa: FBT001
) -> None | str: ...
def save_plot(plt: ModuleType, iternum: int = 0) -> None: ...
